### ISSUE TITLE
ERROR: StringCchVPrintfA failed.

### ISSUE THREAD

**Issue by xieyulin** [tandasat/DumpVTable#1]
ERROR: StringCchVPrintfA failed.
INFO : [CLSID] {**_} 4 _**_
INFO : [CLSID] {**_} 4 _**_Events
INFO : [CLSID] {_**} 5 *_*
ERROR: StringCchVPrintfA failed.
INFO : Information was not obtained form the given file.

**Comment by tandasat** [comment]
Hi, could you tell me what file you tested for? The tool is rather incomplete and I am not maintain it well, but I can quickly take a look at it and be able to fix it.

**Comment by xieyulin** [comment]
hhctrl.ocx /win32
or
MsComm32.ocx

*\* WARNING **
Code of the target file will be executed on your system.
Be careful with malicious files.

Do you want to continue? (y/n): y
ERROR: StringCchVPrintfA failed.
INFO : [CLSID] {4B4B0391-6897-11CF-953F-0020AFC28C3B} 0 HandshakingConstants
INFO : [CLSID] {72F05B40-B530-101B-82B6-000000000014} 0 HandshakeConstants
INFO : [CLSID] {7C4FC790-BE64-11CF-95DA-0020AFC28C3B} 0 ErrorConstants
INFO : [CLSID] {8E6EB360-C3B1-11CF-8E6B-00A0C90F26F8} 0 CommEventConstants
INFO : [CLSID] {00000000-0000-0000-0000-000000000000} 0 OnCommConstants
INFO : [CLSID] {00000000-0000-0000-0000-000000000000} 0 InputModeConstants
INFO : [CLSID] {E6E17E90-DF38-11CF-8E74-00A0C90F26F8} 4 IMSComm
INFO : [CLSID] {648A5602-2C6E-101B-82B6-000000000014} 4 DMSCommEvents
INFO : [CLSID] {648A5600-2C6E-101B-82B6-000000000014} 5 MSComm
ERROR: {648A5600-2C6E-101B-82B6-000000000014} File mismatch [C:\Windows\SysWOW64\MSCOMM32.OCX]
INFO : Information was not obtained form the given file.

**Comment by tandasat** [comment]
I did not find MSCOMM32.OCX and was not reproduce the issue with hhctrl.ocx on my box (Win7 SP1 x64). Let me know if there are any files that cause the same issue and freely available. 

```
C:\Users\user\Desktop\DumpVTable\DumpVTable\Debug>dumpvtable C:\Windows\SysWOW64\hhctrl.ocx out.py -y
INFO : [INFO ] Target = C:\Windows\SysWOW64\hhctrl.ocx
INFO : [CLSID] {ADB880A3-D8FF-11CF-9377-00AA003B7A11} 4 _HHCtrlEvents
INFO : [CLSID] {52A2AAAE-085D-4187-97EA-8C30DB990436} 5 HHCtrl
INFO : [CLSID] {ADB880A1-D8FF-11CF-9377-00AA003B7A11} 4 IHHCtrl
INFO : [CLSID] {00000000-0000-0000-0000-000000000000} 6 UINT_PTR
INFO : [CLSID] {00000000-0000-0000-0000-000000000000} 6 LONG_PTR
INFO : [CLSID] {41B23C28-488E-4E5C-ACE2-BB0BBABE99E8} 5 OldHHCtrl2
INFO : [CLSID] {ADB880A6-D8FF-11CF-9377-00AA003B7A11} 5 OldHHCtrl1
INFO : [VTABLE] 5D0831F0 IHHCtrl
INFO : [METHOD]   7 5D0A71DC IHHCtrl__put_Image
INFO : [METHOD]   8 5D0A60C6 IHHCtrl__get_Image
INFO : [METHOD]   9 5D0A610E IHHCtrl__Click
INFO : [METHOD]  10 5D0A610E IHHCtrl__HHClick
INFO : [METHOD]  11 5D0A61B1 IHHCtrl__Print
INFO : [METHOD]  12 5D0A612C IHHCtrl__syncURL
INFO : [METHOD]  13 5D0A6177 IHHCtrl__TCard
INFO : [METHOD]  14 5D0A61F8 IHHCtrl__TextPopup
INFO : [VTABLE] 5D0831F0 IHHCtrl
INFO : [METHOD]   7 5D0A71DC IHHCtrl__put_Image
INFO : [METHOD]   8 5D0A60C6 IHHCtrl__get_Image
INFO : [METHOD]   9 5D0A610E IHHCtrl__Click
INFO : [METHOD]  10 5D0A610E IHHCtrl__HHClick
INFO : [METHOD]  11 5D0A61B1 IHHCtrl__Print
INFO : [METHOD]  12 5D0A612C IHHCtrl__syncURL
INFO : [METHOD]  13 5D0A6177 IHHCtrl__TCard
INFO : [METHOD]  14 5D0A61F8 IHHCtrl__TextPopup
INFO : [VTABLE] 5D0831F0 IHHCtrl
INFO : [METHOD]   7 5D0A71DC IHHCtrl__put_Image
INFO : [METHOD]   8 5D0A60C6 IHHCtrl__get_Image
INFO : [METHOD]   9 5D0A610E IHHCtrl__Click
INFO : [METHOD]  10 5D0A610E IHHCtrl__HHClick
INFO : [METHOD]  11 5D0A61B1 IHHCtrl__Print
INFO : [METHOD]  12 5D0A612C IHHCtrl__syncURL
INFO : [METHOD]  13 5D0A6177 IHHCtrl__TCard
INFO : [METHOD]  14 5D0A61F8 IHHCtrl__TextPopup
```

**Comment by tandasat** [comment]
Close it for now.
