### ISSUE TITLE
LoadTypeLib error

### ISSUE THREAD

**Issue by killaragorn** [tandasat/DumpVTable#3]
DumpVTable.exe C:\Users\xbot\Desktop\UiPath.dll ../out.py
** WARNING **
Code of the target file will be executed on your system.
Be careful with malicious files.

Do you want to continue? (y/n): y
INFO : [INFO ] Target = C:\Users\xbot\Desktop\DumpVTable-master\DumpVTable\Debug\DumpVTable.exe
ERROR: LoadTypeLibEx returned 80029C4A [加载类型库/DLL 时出错。]
INFO : Information was not obtained form the given file.

**Comment by killaragorn** [comment]
[UiPath.zip](https://github.com/tandasat/DumpVTable/files/9298347/UiPath.zip)

**Comment by tandasat** [comment]
This is normal when the type library is not registered on the system. registry.

If you are unsure compare what registry entries are accessed between against successful file vs that file. `C:\Windows\System32\sysmon.ocx` is a functional example on Windows 11.
